#cat issuer.yml
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: le-prod
spec:
  acme:
    email: waiyanwinhtain@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-key
    solvers:
    - dns01:
        cloudflare:
          email: waiyanwinhtain224@gmail.com
          apiTokenSecretRef:
            name: cloudflare-api-token-secret
            key: api-token
