kind: role
version: v5
metadata:
  name: admin
spec:
  allow:
    kubernetes_groups: ['system:masters']
    node_labels:
      '*': '*'
    kubernetes_labels:
      '*': '*'
    rules:
      - resources: ["*"]
        verbs: ["*"]
