apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: read
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - pods/exec
      - pods/portforward
      - pods/attach
      - services/portforward
    verbs:
      - create
  - apiGroups:
      - ""
    resources:
      - pods
      - deployments
      - services
    verbs:
      - get
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: read-custom
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: read
subjects:
  - kind: Group
    name: read
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: read-view
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
  - kind: Group
    name: read
